### ISSUE TITLE
Trying to get withLocalTmpDir working with oclif test

### ISSUE THREAD

**Issue by markjfisher** [dword-design/with-local-tmp-dir#105]
Hi, I came across your blog and this repo when looking for a clean way to create files during javascript testing.

I'm pretty new to js/ts in general, so this maybe just me doing something wrong.

I've got an oclif application setup I'm trying to test. The cli takes an arg of a file, which I want to create in the test, and use it when running the command, so it reads the generated file.

However, it's not running  my test.

Here's my code:

```javascript
import { expect, test } from '@oclif/test'
import { readFile } from 'fs-extra'

// non type-script libs
var withLocalTmpDir = require('with-local-tmp-dir')
var outputFiles = require('output-files')
var endent = require('endent')

describe('obfuscate', () => {
  withLocalTmpDir(async () => {
    await outputFiles({
      'data.csv': endent`
        name1,name2
        1,v1
        2,v2
      `
    })

  test
    .stdout()
    .command(['obfuscate', '-f=data.csv', '-o=out.csv', '--hasHeader'])
    .it('runs obfuscate cmd', ctx => {
      expect(readFile('out.csv', 'utf8')).to.equal(endent`
          name1,name2
          d3a68ace9732b3b91304b446ac5710fb,v1
          52514e2a3ec1bf72362b7a8799ce6a0d,v2
        `)
    })
  })
})
```
when I run yarn test, it doesn't find anything to run.

oclif [test docs are here](https://oclif.io/docs/testing), and it's an extension of [fancy-test](https://github.com/oclif/fancy-test), so I think this may be not understanding how to chain correctly in js.

So, I think this is because withLocalTmpDir would normally be run within an `it`, but as the `it` is inside withLocalTmp (inside ocli's helper test object) there's nothing going on.

But I can't put the withLocalTmpDir inside the `it`, because the file needs to have been setup before the command is run.

So I'm a bit lost, and wondered if there's a simple solution here that I don't yet understand.
Thanks!

**Comment by dword-design** [comment]
@markjfisher Sorry for the late answer 🙈. First idea is that you are missing `await` before withLocalTmpDir and making the function inside `describe` async. Or you can return directly from withLocalTmpDir, I think `describe` should run async.

**Comment by markjfisher** [comment]
Thanks @dword-design I missed your reply too 🤣 
I haven't touched this in a while, so if I come across it again, I'll see if this helped.
I'll close this, otherwise it'll sit around for another few months :D
